### ISSUE TITLE
Failure on OS X with Homebrew (signatures.conf not found)

### ISSUE THREAD

**Issue by st3fan** [mozilla/minion-skipfish-plugin#16]
The following error appears in the stderr.log:

```
SYSTEM ERROR : Unable to open signature list 'signatures/signatures.conf'
    Stop location : load_signatures(), src/signatures.c:380
       OS message : No such file or directory
```

Maybe 2.10b needs an extra option for this. Needs to be tested on Linux too, to be sure.

**Comment by st3fan** [comment]
It looks like the Homebrew port of Skipfish is broken. It doesn't properly changes the path of the `signatures` directory to point to `/usr/local/Cellar/skipfish/2.10b/libexec/signatures`. We can do a workaround for this, but it won't be super pretty.

**Comment by akaJedi** [comment]
Just install Skipfish from Brew on MacBookPro(Y), and have the same error.
For avoid this error you can use this way
run "skipfish -z /path/to/your/signatures/signatures.conf"
