### ISSUE TITLE
Allow the plugin to find the dictionaries on HomeBrew

### ISSUE THREAD

**Issue by st3fan** [mozilla/minion-skipfish-plugin#9]
On OS X with HomeBrew, the dictionaries are stored in `/usr/local/Cellar/skipfish/2.10b/libexec/dictionaries/`.

Add this path to the list of known paths that we have in `skipfish.py`. Or, add a special case if it needs to detect the path with an unknown version number.

**Comment by yeukhon** [comment]
We can reuse this https://github.com/mozilla/minion-skipfish-plugin/blob/master/minion/plugins/skipfish.py#L216 and do a dynamic replacement. But yes we still need to do a version check against older skipfish.

I prefer to do the fix once I have a Mac OSX vm. Might take a day or two.
